/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MdReaderRouteImport } from './routes/md-reader'
import { Route as CodeStudioRouteImport } from './routes/code-studio'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MdReaderRoute = MdReaderRouteImport.update({
  id: '/md-reader',
  path: '/md-reader',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeStudioRoute = CodeStudioRouteImport.update({
  id: '/code-studio',
  path: '/code-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code-studio': typeof CodeStudioRoute
  '/md-reader': typeof MdReaderRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code-studio': typeof CodeStudioRoute
  '/md-reader': typeof MdReaderRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/code-studio': typeof CodeStudioRoute
  '/md-reader': typeof MdReaderRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/code-studio' | '/md-reader' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/code-studio' | '/md-reader' | '/settings'
  id: '__root__' | '/' | '/code-studio' | '/md-reader' | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeStudioRoute: typeof CodeStudioRoute
  MdReaderRoute: typeof MdReaderRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/md-reader': {
      id: '/md-reader'
      path: '/md-reader'
      fullPath: '/md-reader'
      preLoaderRoute: typeof MdReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-studio': {
      id: '/code-studio'
      path: '/code-studio'
      fullPath: '/code-studio'
      preLoaderRoute: typeof CodeStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeStudioRoute: CodeStudioRoute,
  MdReaderRoute: MdReaderRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
